{% set name = "snorkel" %}
{% set version = "0.9.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/snorkel-team/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: b6af05f4fb9a606fc39115de1906dc4c4f323472d8fb4fc924757062b7289f68

build:

  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy >=1.16.0,<2.0.0
    - scipy >=1.2.0,<2.0.0
    - pandas >=0.24.0,<0.25.0
    - tqdm >=4.29.0,<5.0.0
    - scikit-learn >=0.20.2,<0.22.0
    - pytorch >=1.1.0,<1.2.0
    - networkx >=2.2,<3.0
    - tensorboardX >=1.6,<2.0

test:
  imports:
    - snorkel

about:
  home: https://snorkel.org
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Snorkel is a system for programmatically building and managing training datasets to rapidly and flexibly fuel machine learning models.'

  description: |
    Snorkel is a system for programmatically building and managing training
    datasets to rapidly and flexibly fuel machine learning models.
    Users write programmatic operations to label, transform, and structure training
    datasets for machine learning, without needing to hand label any training data.
    Snorkel then uses modern, theoretically-grounded modeling techniques to clean and
    integrate the resulting training data.
  doc_url: https://snorkel.readthedocs.io
  dev_url: https://github.com/snorkel-team/snorkel

extra:
  recipe-maintainers:
    - henryre
    - adbeda
