travis:
  secure:
    BINSTAR_TOKEN: pzO3WqIsROUGG47PnN3R25tWqn/fzwKLbrXloEJmlvxMuSLD5vkKKI8C6OEL376/5YS3MQhN4K27etjsDzViSGL1pVfDaTVRIQcRqsyGYNi8PG/oJElL0e3pkyUq0lP3hF0pzhP8UaYP+iUP7aJH5/1gQ+wYYTDQCOeQnnEWclcJt8xtqFwWM5oUqIOqDIwkE5zX6zqRofaP6oPGsAtj3QCzDj4KZ5IiSsOOw4BtySfifNepC5NztZMWo199DRBDU4utdeMLWni/TzqdiyJ+BZQHc+gO4Vcl32XG0eY4/7Jo9ZHt2waZ/x9aTRukF4gtQHbXZBUz6VGPrs77Y0yIPDUEpANNmh64Go+tzwZYDO8ZEW14ULLfJFsux51iFnD5Oc6ALA16QzYAbGPBGip17dodc8mXPiFuyoH6kKcJiZYDNizANuRep9m+8vLWp8l/ZkX4p8a2uYW9KA47SyqdOVJqkCwTkmOlnOYU+J7G3Cr27ZDHE56HDzHzne25oBdei97oz303bMPrM/5Vadlr9ZWVJCKiHrxxZmvYQI0CKQmqm4KX6+X/JqPr+XXALaOIw2LgrKGhGVJc8b/Buinvld6XABIHvCOOXoTi+gUyjr0xu8B9xWzy8YlA7E2ELs3uYuSx+uPjY5N3JQV+/0M2mn3J/USYUlo3H4ehF06fw5o=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
